// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
  /**
   * Name field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Job Title field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.job_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField;

  /**
   * Bio field in *Author*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bio: prismic.RichTextField;

  /**
   * Image field in *Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;

type ContactDocumentDataSlicesSlice = never;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Background Color field in *Contact*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: contact.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Tagline field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Title field in *Contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Buttons field in *Contact*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.buttons
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

/**
 * Content for Global documents
 */
interface GlobalDocumentData {
  /**
   * Site Logo field in *Global*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: global.site_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  site_logo: prismic.ImageField<never>;

  /**
   * Site Title field in *Global*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: global.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField /**
   * Address field in *Global*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: global.address
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  address: prismic.KeyTextField;

  /**
   * Email field in *Global*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: global.email
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Phone field in *Global*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: global.phone
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Socials field in *Global*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global.socials
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  socials: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Facebook" | "Twitter" | "Instagram" | "Youtube" | "LinkedIn"
    >
  >;
}

/**
 * Global document from Prismic
 *
 * - **API ID**: `global`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalDocumentData>,
    "global",
    Lang
  >;

/**
 * Item in *Insight → Categories*
 */
export interface InsightDocumentDataCategoriesItem {
  /**
   * Category Name field in *Insight → Categories*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: insight.categories[].name
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  name: prismic.ContentRelationshipField<"insights_categories">;
}

/**
 * Item in *Insight → Authors*
 */
export interface InsightDocumentDataAuthorsItem {
  /**
   * Author field in *Insight → Authors*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: insight.authors[].author
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<"author">;
}

type InsightDocumentDataSlicesSlice = never;

/**
 * Content for Insight documents
 */
interface InsightDocumentData {
  /**
   * Background Color field in *Insight*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: insight.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Tagline field in *Insight*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insight.tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Title field in *Insight*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insight.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Insight*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insight.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Image field in *Insight*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: insight.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Categories field in *Insight*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: insight.categories[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  categories: prismic.GroupField<Simplify<InsightDocumentDataCategoriesItem>>;

  /**
   * Authors field in *Insight*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: insight.authors[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  authors: prismic.GroupField<Simplify<InsightDocumentDataAuthorsItem>>;

  /**
   * Slice Zone field in *Insight*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: insight.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<InsightDocumentDataSlicesSlice> /**
   * Meta Title field in *Insight*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: insight.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Insight*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: insight.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Insight*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: insight.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Insight document from Prismic
 *
 * - **API ID**: `insight`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InsightDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<InsightDocumentData>,
    "insight",
    Lang
  >;

type InsightsCategoriesDocumentDataSlicesSlice = never;

/**
 * Content for Insights Categories documents
 */
interface InsightsCategoriesDocumentData {
  /**
   * Background Color field in *Insights Categories*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: insights_categories.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Title field in *Insights Categories*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insights_categories.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Insights Categories*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insights_categories.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Buttons field in *Insights Categories*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: insights_categories.buttons
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Image field in *Insights Categories*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: insights_categories.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Insights Categories*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: insights_categories.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<InsightsCategoriesDocumentDataSlicesSlice> /**
   * Meta Title field in *Insights Categories*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: insights_categories.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Insights Categories*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: insights_categories.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Insights Categories*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: insights_categories.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Insights Categories document from Prismic
 *
 * - **API ID**: `insights_categories`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InsightsCategoriesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<InsightsCategoriesDocumentData>,
    "insights_categories",
    Lang
  >;

type InsightsListingDocumentDataSlicesSlice = never;

/**
 * Content for Insights Listing documents
 */
interface InsightsListingDocumentData {
  /**
   * Background Color field in *Insights Listing*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: insights_listing.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Tagline field in *Insights Listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insights_listing.tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Title field in *Insights Listing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insights_listing.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Insights Listing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insights_listing.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Buttons field in *Insights Listing*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: insights_listing.buttons
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Image field in *Insights Listing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: insights_listing.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Insights Listing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: insights_listing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<InsightsListingDocumentDataSlicesSlice> /**
   * Meta Title field in *Insights Listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: insights_listing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Insights Listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: insights_listing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Insights Listing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: insights_listing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Insights Listing document from Prismic
 *
 * - **API ID**: `insights_listing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InsightsListingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<InsightsListingDocumentData>,
    "insights_listing",
    Lang
  >;

type MenusDocumentDataSlicesSlice = MenuPanelSlice | SingleLinkSlice;

type MenusDocumentDataSlices1Slice = MultiLinkColumnSlice;

/**
 * Content for Menus documents
 */
interface MenusDocumentData {
  /**
   * Slice Zone field in *Menus*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.slices[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MenusDocumentDataSlicesSlice> /**
   * Footer Links field in *Menus*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.footer_links
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */;
  footer_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Copyright field in *Menus*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.copyright
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;

  /**
   * Slice Zone field in *Menus*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.slices1[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<MenusDocumentDataSlices1Slice> /**
   * Banner Text field in *Menus*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.banner_text
   * - **Tab**: Announcement
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  banner_text: prismic.RichTextField;
}

/**
 * Menus document from Prismic
 *
 * - **API ID**: `menus`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenusDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenusDocumentData>, "menus", Lang>;

type PageDocumentDataSlicesSlice =
  | TestimonialsSlice
  | TileGridSlice
  | SimpleTextSlice
  | ImageTextSlice
  | HorizontalAccordionSlice
  | NumberedListSlice
  | ContentCarouselSlice
  | ContentColumnSlice
  | CtaBannerSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Background Color field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: page.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Tagline field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Buttons field in *Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page.buttons
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ServiceDocumentDataSlicesSlice = never;

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * Background Color field in *Service*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: service.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Tagline field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Title field in *Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Buttons field in *Service*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service.buttons
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Image field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Service*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServiceDocumentDataSlicesSlice> /**
   * Meta Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: service.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: service.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDocumentData>,
    "service",
    Lang
  >;

type ServicesListingDocumentDataSlicesSlice = never;

/**
 * Content for Services Listing documents
 */
interface ServicesListingDocumentData {
  /**
   * Background Color field in *Services Listing*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: services_listing.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Title field in *Services Listing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_listing.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Services Listing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_listing.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *Services Listing*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_listing.button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Image field in *Services Listing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_listing.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Services Listing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services_listing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicesListingDocumentDataSlicesSlice> /**
   * Meta Title field in *Services Listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: services_listing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Services Listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: services_listing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services Listing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_listing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Services Listing document from Prismic
 *
 * - **API ID**: `services_listing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesListingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServicesListingDocumentData>,
    "services_listing",
    Lang
  >;

type TeamDocumentDataSlicesSlice = CtaBannerSlice | TeamListSlice;

/**
 * Content for Team documents
 */
interface TeamDocumentData {
  /**
   * Background Color field in *Team*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: team.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Tagline field in *Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Title field in *Team*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Team*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Buttons field in *Team*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team.buttons
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Image field in *Team*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Team*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: team.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TeamDocumentDataSlicesSlice> /**
   * Meta Title field in *Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: team.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: team.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Team*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Team document from Prismic
 *
 * - **API ID**: `team`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<TeamDocumentData>, "team", Lang>;

export type AllDocumentTypes =
  | AuthorDocument
  | ContactDocument
  | GlobalDocument
  | InsightDocument
  | InsightsCategoriesDocument
  | InsightsListingDocument
  | MenusDocument
  | PageDocument
  | ServiceDocument
  | ServicesListingDocument
  | TeamDocument;

/**
 * Item in *ContentCarousel → Default (Insight) → Primary → Cards*
 */
export interface ContentCarouselSliceDefaultPrimaryCardsItem {
  /**
   * Item field in *ContentCarousel → Default (Insight) → Primary → Cards*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: content_carousel.default.primary.cards[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<"insight">;
}

/**
 * Item in *ContentCarousel → ManualCarousel (Our Works) → Primary → Cards*
 */
export interface ContentCarouselSliceManualCarouselPrimaryCardsItem {
  /**
   * Image field in *ContentCarousel → ManualCarousel (Our Works) → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_carousel.manualCarousel.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ContentCarousel → ManualCarousel (Our Works) → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_carousel.manualCarousel.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *ContentCarousel → ManualCarousel (Our Works) → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_carousel.manualCarousel.primary.cards[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Tags field in *ContentCarousel → ManualCarousel (Our Works) → Primary → Cards*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: content_carousel.manualCarousel.primary.cards[].tags
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tags: prismic.ContentRelationshipField<"insights_categories">;

  /**
   * Buttons field in *ContentCarousel → ManualCarousel (Our Works) → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_carousel.manualCarousel.primary.cards[].buttons
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Primary content in *ContentCarousel → Default (Insight) → Primary*
 */
export interface ContentCarouselSliceDefaultPrimary {
  /**
   * Background Color field in *ContentCarousel → Default (Insight) → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: content_carousel.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Title field in *ContentCarousel → Default (Insight) → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_carousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *ContentCarousel → Default (Insight) → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_carousel.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Cards field in *ContentCarousel → Default (Insight) → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content_carousel.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<
    Simplify<ContentCarouselSliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default (Insight) variation for ContentCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ContentCarousel → ManualCarousel (Our Works) → Primary*
 */
export interface ContentCarouselSliceManualCarouselPrimary {
  /**
   * Background Color field in *ContentCarousel → ManualCarousel (Our Works) → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: content_carousel.manualCarousel.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Title field in *ContentCarousel → ManualCarousel (Our Works) → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_carousel.manualCarousel.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *ContentCarousel → ManualCarousel (Our Works) → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_carousel.manualCarousel.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Cards field in *ContentCarousel → ManualCarousel (Our Works) → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content_carousel.manualCarousel.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<
    Simplify<ContentCarouselSliceManualCarouselPrimaryCardsItem>
  >;
}

/**
 * ManualCarousel (Our Works) variation for ContentCarousel Slice
 *
 * - **API ID**: `manualCarousel`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentCarouselSliceManualCarousel = prismic.SharedSliceVariation<
  "manualCarousel",
  Simplify<ContentCarouselSliceManualCarouselPrimary>,
  never
>;

/**
 * Slice variation for *ContentCarousel*
 */
type ContentCarouselSliceVariation =
  | ContentCarouselSliceDefault
  | ContentCarouselSliceManualCarousel;

/**
 * ContentCarousel Shared Slice
 *
 * - **API ID**: `content_carousel`
 * - **Description**: ContentCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentCarouselSlice = prismic.SharedSlice<
  "content_carousel",
  ContentCarouselSliceVariation
>;

/**
 * Item in *ContentColumn → Default → Primary → Content*
 */
export interface ContentColumnSliceDefaultPrimaryContentItem {
  /**
   * Icon field in *ContentColumn → Default → Primary → Content*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_column.default.primary.content[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *ContentColumn → Default → Primary → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_column.default.primary.content[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *ContentColumn → Default → Primary → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_column.default.primary.content[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Item in *ContentColumn → ContentColumn with Cards → Primary → Content*
 */
export interface ContentColumnSliceContentColumnWithCardsPrimaryContentItem {
  /**
   * Icon field in *ContentColumn → ContentColumn with Cards → Primary → Content*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_column.contentColumnWithCards.primary.content[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *ContentColumn → ContentColumn with Cards → Primary → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_column.contentColumnWithCards.primary.content[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *ContentColumn → ContentColumn with Cards → Primary → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_column.contentColumnWithCards.primary.content[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *ContentColumn → Default → Primary*
 */
export interface ContentColumnSliceDefaultPrimary {
  /**
   * Background Color field in *ContentColumn → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: content_column.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Title field in *ContentColumn → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_column.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *ContentColumn → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_column.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Content Tile Color field in *ContentColumn → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Default
   * - **API ID Path**: content_column.default.primary.tile_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tile_color: prismic.SelectField<
    "Default" | "Light" | "Dark" | "Outline" | "No Border",
    "filled"
  >;

  /**
   * Show Icon field in *ContentColumn → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: content_column.default.primary.show_icon
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_icon: prismic.BooleanField;

  /**
   * Content field in *ContentColumn → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content_column.default.primary.content[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content: prismic.GroupField<
    Simplify<ContentColumnSliceDefaultPrimaryContentItem>
  >;
}

/**
 * Default variation for ContentColumn Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentColumnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentColumnSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ContentColumn → ContentColumn with Cards → Primary*
 */
export interface ContentColumnSliceContentColumnWithCardsPrimary {
  /**
   * Background Color field in *ContentColumn → ContentColumn with Cards → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: content_column.contentColumnWithCards.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Title field in *ContentColumn → ContentColumn with Cards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_column.contentColumnWithCards.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *ContentColumn → ContentColumn with Cards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_column.contentColumnWithCards.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Content Tile Color field in *ContentColumn → ContentColumn with Cards → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Default
   * - **API ID Path**: content_column.contentColumnWithCards.primary.tile_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tile_color: prismic.SelectField<
    "Default" | "Light" | "Dark" | "Outline" | "No Border",
    "filled"
  >;

  /**
   * Show Icon field in *ContentColumn → ContentColumn with Cards → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: content_column.contentColumnWithCards.primary.show_icon
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_icon: prismic.BooleanField;

  /**
   * Content field in *ContentColumn → ContentColumn with Cards → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content_column.contentColumnWithCards.primary.content[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content: prismic.GroupField<
    Simplify<ContentColumnSliceContentColumnWithCardsPrimaryContentItem>
  >;
}

/**
 * ContentColumn with Cards variation for ContentColumn Slice
 *
 * - **API ID**: `contentColumnWithCards`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentColumnSliceContentColumnWithCards =
  prismic.SharedSliceVariation<
    "contentColumnWithCards",
    Simplify<ContentColumnSliceContentColumnWithCardsPrimary>,
    never
  >;

/**
 * Slice variation for *ContentColumn*
 */
type ContentColumnSliceVariation =
  | ContentColumnSliceDefault
  | ContentColumnSliceContentColumnWithCards;

/**
 * ContentColumn Shared Slice
 *
 * - **API ID**: `content_column`
 * - **Description**: ContentColumn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentColumnSlice = prismic.SharedSlice<
  "content_column",
  ContentColumnSliceVariation
>;

/**
 * Primary content in *CtaBanner → Default → Primary*
 */
export interface CtaBannerSliceDefaultPrimary {
  /**
   * Text Alignment field in *CtaBanner → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: cta_banner.default.primary.text_alignment
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  text_alignment: prismic.BooleanField;

  /**
   * Inner Background Color field in *CtaBanner → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Default
   * - **API ID Path**: cta_banner.default.primary.inner_background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  inner_background_color: prismic.SelectField<"Default" | "Gradient", "filled">;

  /**
   * Title field in *CtaBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_banner.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *CtaBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_banner.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Buttons field in *CtaBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_banner.default.primary.buttons
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for CtaBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaBannerSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CtaBanner → CtaBanner - With Form → Primary*
 */
export interface CtaBannerSliceCtaBannerWithFormPrimary {
  /**
   * Text Alignment field in *CtaBanner → CtaBanner - With Form → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: cta_banner.ctaBannerWithForm.primary.text_alignment
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  text_alignment: prismic.BooleanField;

  /**
   * Inner Background Color field in *CtaBanner → CtaBanner - With Form → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Default
   * - **API ID Path**: cta_banner.ctaBannerWithForm.primary.inner_background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  inner_background_color: prismic.SelectField<"Default" | "Gradient", "filled">;

  /**
   * Title field in *CtaBanner → CtaBanner - With Form → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_banner.ctaBannerWithForm.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *CtaBanner → CtaBanner - With Form → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_banner.ctaBannerWithForm.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Buttons field in *CtaBanner → CtaBanner - With Form → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_banner.ctaBannerWithForm.primary.buttons
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Form field in *CtaBanner → CtaBanner - With Form → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_banner.ctaBannerWithForm.primary.form
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  form: prismic.EmbedField;
}

/**
 * CtaBanner - With Form variation for CtaBanner Slice
 *
 * - **API ID**: `ctaBannerWithForm`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaBannerSliceCtaBannerWithForm = prismic.SharedSliceVariation<
  "ctaBannerWithForm",
  Simplify<CtaBannerSliceCtaBannerWithFormPrimary>,
  never
>;

/**
 * Slice variation for *CtaBanner*
 */
type CtaBannerSliceVariation =
  | CtaBannerSliceDefault
  | CtaBannerSliceCtaBannerWithForm;

/**
 * CtaBanner Shared Slice
 *
 * - **API ID**: `cta_banner`
 * - **Description**: CtaBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaBannerSlice = prismic.SharedSlice<
  "cta_banner",
  CtaBannerSliceVariation
>;

/**
 * Item in *HorizontalAccordion → Default → Primary → Accordion*
 */
export interface HorizontalAccordionSliceDefaultPrimaryAccordionItem {
  /**
   * Icon field in *HorizontalAccordion → Default → Primary → Accordion*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: horizontal_accordion.default.primary.accordion[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *HorizontalAccordion → Default → Primary → Accordion*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: horizontal_accordion.default.primary.accordion[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *HorizontalAccordion → Default → Primary → Accordion*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: horizontal_accordion.default.primary.accordion[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Buttons field in *HorizontalAccordion → Default → Primary → Accordion*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: horizontal_accordion.default.primary.accordion[].buttons
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Primary content in *HorizontalAccordion → Default → Primary*
 */
export interface HorizontalAccordionSliceDefaultPrimary {
  /**
   * Background Color field in *HorizontalAccordion → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: horizontal_accordion.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Title field in *HorizontalAccordion → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: horizontal_accordion.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *HorizontalAccordion → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: horizontal_accordion.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Buttons field in *HorizontalAccordion → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: horizontal_accordion.default.primary.buttons
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Accordion field in *HorizontalAccordion → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: horizontal_accordion.default.primary.accordion[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  accordion: prismic.GroupField<
    Simplify<HorizontalAccordionSliceDefaultPrimaryAccordionItem>
  >;
}

/**
 * Default variation for HorizontalAccordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HorizontalAccordionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HorizontalAccordionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HorizontalAccordion*
 */
type HorizontalAccordionSliceVariation = HorizontalAccordionSliceDefault;

/**
 * HorizontalAccordion Shared Slice
 *
 * - **API ID**: `horizontal_accordion`
 * - **Description**: HorizontalAccordion
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HorizontalAccordionSlice = prismic.SharedSlice<
  "horizontal_accordion",
  HorizontalAccordionSliceVariation
>;

/**
 * Item in *ImageText → Stats → Primary → Stats*
 */
export interface ImageTextSliceStatsPrimaryStatsItem {
  /**
   * Statistic field in *ImageText → Stats → Primary → Stats*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.stats.primary.stats[].statistic
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  statistic: prismic.RichTextField;

  /**
   * Description field in *ImageText → Stats → Primary → Stats*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.stats.primary.stats[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Percentage field in *ImageText → Stats → Primary → Stats*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_text.stats.primary.stats[].percentage
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  percentage: prismic.BooleanField;
}

/**
 * Primary content in *ImageText → Default → Primary*
 */
export interface ImageTextSliceDefaultPrimary {
  /**
   * Background Color field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: image_text.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Image Orientation field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_text.default.primary.imageRight
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  imageRight: prismic.BooleanField;

  /**
   * Title field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Body field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Image field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageText → Stats → Primary*
 */
export interface ImageTextSliceStatsPrimary {
  /**
   * Background Color field in *ImageText → Stats → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: image_text.stats.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Image Orientation field in *ImageText → Stats → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_text.stats.primary.imageRight
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  imageRight: prismic.BooleanField;

  /**
   * Title field in *ImageText → Stats → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.stats.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *ImageText → Stats → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.stats.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Body field in *ImageText → Stats → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.stats.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *ImageText → Stats → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.stats.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Image field in *ImageText → Stats → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.stats.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Stats field in *ImageText → Stats → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.stats.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stats: prismic.GroupField<Simplify<ImageTextSliceStatsPrimaryStatsItem>>;
}

/**
 * Stats variation for ImageText Slice
 *
 * - **API ID**: `stats`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSliceStats = prismic.SharedSliceVariation<
  "stats",
  Simplify<ImageTextSliceStatsPrimary>,
  never
>;

/**
 * Primary content in *ImageText → Video → Primary*
 */
export interface ImageTextSliceVideoPrimary {
  /**
   * Background Color field in *ImageText → Video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: image_text.video.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Image Orientation field in *ImageText → Video → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_text.video.primary.imageRight
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  imageRight: prismic.BooleanField;

  /**
   * Title field in *ImageText → Video → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.video.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *ImageText → Video → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.video.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Body field in *ImageText → Video → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.video.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *ImageText → Video → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.video.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Image field in *ImageText → Video → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.video.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *ImageText → Video → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.video.primary.video
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video: prismic.EmbedField;
}

/**
 * Video variation for ImageText Slice
 *
 * - **API ID**: `video`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSliceVideo = prismic.SharedSliceVariation<
  "video",
  Simplify<ImageTextSliceVideoPrimary>,
  never
>;

/**
 * Slice variation for *ImageText*
 */
type ImageTextSliceVariation =
  | ImageTextSliceDefault
  | ImageTextSliceStats
  | ImageTextSliceVideo;

/**
 * ImageText Shared Slice
 *
 * - **API ID**: `image_text`
 * - **Description**: ImageText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSlice = prismic.SharedSlice<
  "image_text",
  ImageTextSliceVariation
>;

/**
 * Item in *MenuPanel → Default → Primary → Link with Paragraph*
 */
export interface MenuPanelSliceDefaultPrimaryLinkWithParagraphItem {
  /**
   * Title field in *MenuPanel → Default → Primary → Link with Paragraph*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.default.primary.link_with_paragraph[].title
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  title: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Body field in *MenuPanel → Default → Primary → Link with Paragraph*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.default.primary.link_with_paragraph[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *MenuPanel → Default → Primary*
 */
export interface MenuPanelSliceDefaultPrimary {
  /**
   * Menu Display field in *MenuPanel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.default.primary.menu_display
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_display: prismic.KeyTextField;

  /**
   * Title field in *MenuPanel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *MenuPanel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Columns field in *MenuPanel → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: menu_panel.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  columns: prismic.BooleanField;

  /**
   * Links field in *MenuPanel → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.default.primary.links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Link with Paragraph field in *MenuPanel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.default.primary.link_with_paragraph[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  link_with_paragraph: prismic.GroupField<
    Simplify<MenuPanelSliceDefaultPrimaryLinkWithParagraphItem>
  >;
}

/**
 * Default variation for MenuPanel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuPanelSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenuPanelSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MenuPanel*
 */
type MenuPanelSliceVariation = MenuPanelSliceDefault;

/**
 * MenuPanel Shared Slice
 *
 * - **API ID**: `menu_panel`
 * - **Description**: MenuPanel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuPanelSlice = prismic.SharedSlice<
  "menu_panel",
  MenuPanelSliceVariation
>;

/**
 * Primary content in *MultiLinkColumn → Default → Primary*
 */
export interface MultiLinkColumnSliceDefaultPrimary {
  /**
   * Title field in *MultiLinkColumn → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_link_column.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Link field in *MultiLinkColumn → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_link_column.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for MultiLinkColumn Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MultiLinkColumnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MultiLinkColumnSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MultiLinkColumn*
 */
type MultiLinkColumnSliceVariation = MultiLinkColumnSliceDefault;

/**
 * MultiLinkColumn Shared Slice
 *
 * - **API ID**: `multi_link_column`
 * - **Description**: MultiLinkColumn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MultiLinkColumnSlice = prismic.SharedSlice<
  "multi_link_column",
  MultiLinkColumnSliceVariation
>;

/**
 * Item in *NumberedList → Default → Primary → List*
 */
export interface NumberedListSliceDefaultPrimaryListItem {
  /**
   * Title field in *NumberedList → Default → Primary → List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: numbered_list.default.primary.list[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *NumberedList → Default → Primary → List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: numbered_list.default.primary.list[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *NumberedList → Default → Primary*
 */
export interface NumberedListSliceDefaultPrimary {
  /**
   * Title field in *NumberedList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: numbered_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *NumberedList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: numbered_list.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * List field in *NumberedList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: numbered_list.default.primary.list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list: prismic.GroupField<Simplify<NumberedListSliceDefaultPrimaryListItem>>;
}

/**
 * Default variation for NumberedList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NumberedListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NumberedListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NumberedList*
 */
type NumberedListSliceVariation = NumberedListSliceDefault;

/**
 * NumberedList Shared Slice
 *
 * - **API ID**: `numbered_list`
 * - **Description**: NumberedList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NumberedListSlice = prismic.SharedSlice<
  "numbered_list",
  NumberedListSliceVariation
>;

/**
 * Primary content in *SimpleText → Default → Primary*
 */
export interface SimpleTextSliceDefaultPrimary {
  /**
   * Text Alignment field in *SimpleText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: simple_text.default.primary.text_alignment
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  text_alignment: prismic.BooleanField;

  /**
   * Text field in *SimpleText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for SimpleText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SimpleTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SimpleText*
 */
type SimpleTextSliceVariation = SimpleTextSliceDefault;

/**
 * SimpleText Shared Slice
 *
 * - **API ID**: `simple_text`
 * - **Description**: SimpleText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleTextSlice = prismic.SharedSlice<
  "simple_text",
  SimpleTextSliceVariation
>;

/**
 * Primary content in *SingleLink → Default → Primary*
 */
export interface SingleLinkSliceDefaultPrimary {
  /**
   * Icon field in *SingleLink → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: single_link.default.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Link field in *SingleLink → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: single_link.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Button Type field in *SingleLink → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Text
   * - **API ID Path**: single_link.default.primary.button_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_type: prismic.SelectField<
    "Text" | "Primary" | "Secondary" | "Outline",
    "filled"
  >;
}

/**
 * Default variation for SingleLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleLinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SingleLinkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SingleLink*
 */
type SingleLinkSliceVariation = SingleLinkSliceDefault;

/**
 * SingleLink Shared Slice
 *
 * - **API ID**: `single_link`
 * - **Description**: SingleLink
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleLinkSlice = prismic.SharedSlice<
  "single_link",
  SingleLinkSliceVariation
>;

/**
 * Item in *TeamList → Default → Primary → Team Member*
 */
export interface TeamListSliceDefaultPrimaryTeamMemberItem {
  /**
   * Image field in *TeamList → Default → Primary → Team Member*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.team_member[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *TeamList → Default → Primary → Team Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.team_member[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Position field in *TeamList → Default → Primary → Team Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.team_member[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;
}

/**
 * Primary content in *TeamList → Default → Primary*
 */
export interface TeamListSliceDefaultPrimary {
  /**
   * Background Color field in *TeamList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: team_list.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Title field in *TeamList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *TeamList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Team Member field in *TeamList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.team_member[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  team_member: prismic.GroupField<
    Simplify<TeamListSliceDefaultPrimaryTeamMemberItem>
  >;
}

/**
 * Default variation for TeamList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeamList*
 */
type TeamListSliceVariation = TeamListSliceDefault;

/**
 * TeamList Shared Slice
 *
 * - **API ID**: `team_list`
 * - **Description**: TeamList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamListSlice = prismic.SharedSlice<
  "team_list",
  TeamListSliceVariation
>;

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Background Color field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: testimonials.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"None" | "Light" | "Dark", "filled">;

  /**
   * Title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Author field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Author Title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.author_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_title: prismic.KeyTextField;

  /**
   * Image field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Default variation for TileGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TileGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TileGrid*
 */
type TileGridSliceVariation = TileGridSliceDefault;

/**
 * TileGrid Shared Slice
 *
 * - **API ID**: `tile_grid`
 * - **Description**: TileGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TileGridSlice = prismic.SharedSlice<
  "tile_grid",
  TileGridSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AuthorDocument,
      AuthorDocumentData,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      GlobalDocument,
      GlobalDocumentData,
      InsightDocument,
      InsightDocumentData,
      InsightDocumentDataCategoriesItem,
      InsightDocumentDataAuthorsItem,
      InsightDocumentDataSlicesSlice,
      InsightsCategoriesDocument,
      InsightsCategoriesDocumentData,
      InsightsCategoriesDocumentDataSlicesSlice,
      InsightsListingDocument,
      InsightsListingDocumentData,
      InsightsListingDocumentDataSlicesSlice,
      MenusDocument,
      MenusDocumentData,
      MenusDocumentDataSlicesSlice,
      MenusDocumentDataSlices1Slice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ServiceDocument,
      ServiceDocumentData,
      ServiceDocumentDataSlicesSlice,
      ServicesListingDocument,
      ServicesListingDocumentData,
      ServicesListingDocumentDataSlicesSlice,
      TeamDocument,
      TeamDocumentData,
      TeamDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContentCarouselSlice,
      ContentCarouselSliceDefaultPrimaryCardsItem,
      ContentCarouselSliceDefaultPrimary,
      ContentCarouselSliceManualCarouselPrimaryCardsItem,
      ContentCarouselSliceManualCarouselPrimary,
      ContentCarouselSliceVariation,
      ContentCarouselSliceDefault,
      ContentCarouselSliceManualCarousel,
      ContentColumnSlice,
      ContentColumnSliceDefaultPrimaryContentItem,
      ContentColumnSliceDefaultPrimary,
      ContentColumnSliceContentColumnWithCardsPrimaryContentItem,
      ContentColumnSliceContentColumnWithCardsPrimary,
      ContentColumnSliceVariation,
      ContentColumnSliceDefault,
      ContentColumnSliceContentColumnWithCards,
      CtaBannerSlice,
      CtaBannerSliceDefaultPrimary,
      CtaBannerSliceCtaBannerWithFormPrimary,
      CtaBannerSliceVariation,
      CtaBannerSliceDefault,
      CtaBannerSliceCtaBannerWithForm,
      HorizontalAccordionSlice,
      HorizontalAccordionSliceDefaultPrimaryAccordionItem,
      HorizontalAccordionSliceDefaultPrimary,
      HorizontalAccordionSliceVariation,
      HorizontalAccordionSliceDefault,
      ImageTextSlice,
      ImageTextSliceDefaultPrimary,
      ImageTextSliceStatsPrimaryStatsItem,
      ImageTextSliceStatsPrimary,
      ImageTextSliceVideoPrimary,
      ImageTextSliceVariation,
      ImageTextSliceDefault,
      ImageTextSliceStats,
      ImageTextSliceVideo,
      MenuPanelSlice,
      MenuPanelSliceDefaultPrimaryLinkWithParagraphItem,
      MenuPanelSliceDefaultPrimary,
      MenuPanelSliceVariation,
      MenuPanelSliceDefault,
      MultiLinkColumnSlice,
      MultiLinkColumnSliceDefaultPrimary,
      MultiLinkColumnSliceVariation,
      MultiLinkColumnSliceDefault,
      NumberedListSlice,
      NumberedListSliceDefaultPrimaryListItem,
      NumberedListSliceDefaultPrimary,
      NumberedListSliceVariation,
      NumberedListSliceDefault,
      SimpleTextSlice,
      SimpleTextSliceDefaultPrimary,
      SimpleTextSliceVariation,
      SimpleTextSliceDefault,
      SingleLinkSlice,
      SingleLinkSliceDefaultPrimary,
      SingleLinkSliceVariation,
      SingleLinkSliceDefault,
      TeamListSlice,
      TeamListSliceDefaultPrimaryTeamMemberItem,
      TeamListSliceDefaultPrimary,
      TeamListSliceVariation,
      TeamListSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TileGridSlice,
      TileGridSliceVariation,
      TileGridSliceDefault,
    };
  }
}
