// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  content_carousel: dynamic(() => import("./ContentCarousel")),
  content_column: dynamic(() => import("./ContentColumn")),
  cta_banner: dynamic(() => import("./CtaBanner")),
  horizontal_accordion: dynamic(() => import("./HorizontalAccordion")),
  image_text: dynamic(() => import("./ImageText")),
  menu_panel: dynamic(() => import("./MenuPanel")),
  multi_link_column: dynamic(() => import("./MultiLinkColumn")),
  numbered_list: dynamic(() => import("./NumberedList")),
  simple_text: dynamic(() => import("./SimpleText")),
  single_link: dynamic(() => import("./SingleLink")),
  team_list: dynamic(() => import("./TeamList")),
  testimonials: dynamic(() => import("./Testimonials")),
  tile_grid: dynamic(() => import("./TileGrid")),
};
