// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  content_carousel: dynamic(() => import("./ContentCarousel")),
  content_column: dynamic(() => import("./ContentColumn")),
  content_grid: dynamic(() => import("./ContentGrid")),
  cta_banner: dynamic(() => import("./CtaBanner")),
  horizontal_accordion: dynamic(() => import("./HorizontalAccordion")),
  image_text: dynamic(() => import("./ImageText")),
  menu_panel: dynamic(() => import("./MenuPanel")),
  multi_link_column: dynamic(() => import("./MultiLinkColumn")),
  numbered_list: dynamic(() => import("./NumberedList")),
  price_cards: dynamic(() => import("./PriceCards")),
  simple_text: dynamic(() => import("./SimpleText")),
  single_link: dynamic(() => import("./SingleLink")),
  stats: dynamic(() => import("./Stats")),
  team_list: dynamic(() => import("./TeamList")),
  testimonials: dynamic(() => import("./Testimonials")),
};
